services:

  postgres:
    image: postgres:16

    container_name: techplanner-postgres

    environment:
      POSTGRES_DB: techplanner
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  techplanner-quotation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techplanner-quotation-service
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techplanner
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: