apiVersion: v1
kind: Service
metadata:
  name: quotation-service
  namespace: quotation-service
  labels:
    app.kubernetes.io/name: quotation-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: techplanner
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: quotation-service
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
